import Link from 'next/link'
import { UserButton, SignInButton, SignUpButton, useUser } from '@clerk/nextjs'

interface FeatureCardProps {
        title: string;
          description: string;
            icon: string;
            }


           
              

                             
                                    


export default function LandingPage() {
  const { isSignedIn } = useUser()






    return (
        <div className="min-h-screen bg-gradient-to-b from-blue-100 to-white">
              <header className="container mx-auto px-4 py-6 flex justify-between items-center">
                      <h1 className="text-3xl font-bold text-blue-600">Mass DM Sender</h1>
                              <nav>
                                        {isSignedIn ? (
                                                    <div className="flex items-center space-x-4">
                                                                  <Link href="/dashboard" className="text-blue-600 hover:text-blue-800">
                                                                                  Dashboard
                                                                                                </Link>
                                                                                                              <UserButton afterSignOutUrl="/" />
                                                                                                                          </div>
                                                                                                                                    ) : (
                                                                                                                                                <div className="space-x-4">
                                                                                                                                                              <SignInButton mode="modal">
                                                                                                                                                                              <button className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">
                                                                                                                                                                                                Sign In
                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                              </SignInButton>
                                                                                                                                                                                                                                            <SignUpButton mode="modal">
                                                                                                                                                                                                                                                            <button className="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded">
                                                                                                                                                                                                                                                                              Sign Up
                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                            </SignUpButton>
                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                          </nav>
                                                                                                                                                                                                                                                                                                                                                </header>

                                                                                                                                                                                                                                                                                                                                                      <main className="container mx-auto px-4 py-16">
                                                                                                                                                                                                                                                                                                                                                              <div className="text-center mb-16">
                                                                                                                                                                                                                                                                                                                                                                        <h2 className="text-5xl font-bold mb-4">Streamline Your Social Media Outreach</h2>
                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-xl text-gray-600 mb-8">
                                                                                                                                                                                                                                                                                                                                                                                              Efficiently manage and automate your direct messaging campaigns across multiple platforms.
                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                  {!isSignedIn && (
                                                                                                                                                                                                                                                                                                                                                                                                                              <SignUpButton mode="modal">
                                                                                                                                                                                                                                                                                                                                                                                                                                            <button className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-3 px-6 rounded-lg text-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            Get Started For Free
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </SignUpButton>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="grid md:grid-cols-3 gap-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <FeatureCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title="Multi-Platform Support"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  description="Manage campaigns across Instagram, Twitter, and LinkedIn from a single dashboard."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              icon="🌐"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <FeatureCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title="Anti-Detection Technology"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          description="Our advanced system mimics human behavior to minimize the risk of account restrictions."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      icon="🛡️"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <FeatureCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title="Detailed Analytics"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  description="Track your campaign performance with in-depth analytics and reporting tools."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              icon="📊"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <footer className="bg-gray-100 mt-16">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="container mx-auto px-4 py-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-600">© 2023 Mass DM Sender. All rights reserved.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="space-x-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link href="/privacy" className="text-gray-600 hover:text-gray-800">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Privacy Policy
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link href="/terms" className="text-gray-600 hover:text-gray-800">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Terms of Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function FeatureCard({ title, description, icon } : FeatureCardProps) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-white p-6 rounded-lg shadow-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="text-4xl mb-4">{icon}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="text-xl font-semibold mb-2">{title}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-gray-600">{description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }