// src/components/accounts/AccountForm.jsx
import React, { useState, useEffect } from 'react';
import  useAccounts from '../../hooks/useAccounts';

const PLATFORMS = ['Instagram', 'Twitter', 'LinkedIn', 'Facebook'];

const AccountForm = ({ initialData, onSuccess, onCancel }) => {
  const [formData, setFormData] = useState({
      username: '',
          password: '',
              platform: '',
                  proxy: '',
                      userAgent: '',
                          status: 'active',
                              ...initialData
                                });

                                  const [errors, setErrors] = useState({});
                                    const { addAccount, updateAccount } = useAccounts();

                                      useEffect(() => {
                                          if (initialData) {
                                                setFormData(initialData);
                                                    }
                                                      }, [initialData]);

                                                        const handleChange = (e) => {
                                                            const { name, value } = e.target;
                                                                setFormData(prevData => ({
                                                                      ...prevData,
                                                                            [name]: value
                                                                                }));
                                                                                    // Clear error when user starts typing
                                                                                        if (errors[name]) {
                                                                                              setErrors(prevErrors => ({ ...prevErrors, [name]: '' }));
                                                                                                  }
                                                                                                    };

                                                                                                      const validateForm = () => {
                                                                                                          const newErrors = {};
                                                                                                              if (!formData.username.trim()) newErrors.username = 'Username is required';
                                                                                                                  if (!formData.password.trim()) newErrors.password = 'Password is required';
                                                                                                                      if (!formData.platform) newErrors.platform = 'Platform is required';
                                                                                                                          if (!formData.proxy.trim()) newErrors.proxy = 'Proxy is required';
                                                                                                                              return newErrors;
                                                                                                                                };

                                                                                                                                  const handleSubmit = async (e) => {
                                                                                                                                      e.preventDefault();
                                                                                                                                          const newErrors = validateForm();
                                                                                                                                              if (Object.keys(newErrors).length > 0) {
                                                                                                                                                    setErrors(newErrors);
                                                                                                                                                          return;
                                                                                                                                                              }

                                                                                                                                                                  try {
                                                                                                                                                                        if (initialData) {
                                                                                                                                                                                await updateAccount(initialData.id, formData);
                                                                                                                                                                                      } else {
                                                                                                                                                                                              await addAccount(formData);
                                                                                                                                                                                                    }
                                                                                                                                                                                                          onSuccess();
                                                                                                                                                                                                              } catch (error) {
                                                                                                                                                                                                                    console.error('Failed to save account:', error);
                                                                                                                                                                                                                          setErrors({ submit: 'Failed to save account. Please try again.' });
                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                      <form onSubmit={handleSubmit} className="space-y-4">
                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                    <label htmlFor="username" className="block text-sm font-medium text-gray-700">Username</label>
                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                      type="text"
                                                                                                                                                                                                                                                                                id="username"
                                                                                                                                                                                                                                                                                          name="username"
                                                                                                                                                                                                                                                                                                    value={formData.username}
                                                                                                                                                                                                                                                                                                              onChange={handleChange}
                                                                                                                                                                                                                                                                                                                        className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                        {errors.username && <p className="mt-2 text-sm text-red-600">{errors.username}</p>}
                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                            <label htmlFor="password" className="block text-sm font-medium text-gray-700">Password</label>
                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                              type="password"
                                                                                                                                                                                                                                                                                                                                                                                        id="password"
                                                                                                                                                                                                                                                                                                                                                                                                  name="password"
                                                                                                                                                                                                                                                                                                                                                                                                            value={formData.password}
                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                {errors.password && <p className="mt-2 text-sm text-red-600">{errors.password}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label htmlFor="platform" className="block text-sm font-medium text-gray-700">Platform</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      id="platform"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name="platform"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={formData.platform}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="">Select a platform</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {PLATFORMS.map(platform => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option key={platform} value={platform}>{platform}</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {errors.platform && <p className="mt-2 text-sm text-red-600">{errors.platform}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label htmlFor="proxy" className="block text-sm font-medium text-gray-700">Proxy</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                id="proxy"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          name="proxy"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={formData.proxy}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="ip:port or ip:port:username:password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {errors.proxy && <p className="mt-2 text-sm text-red-600">{errors.proxy}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label htmlFor="userAgent" className="block text-sm font-medium text-gray-700">User Agent</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  id="userAgent"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            name="userAgent"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={formData.userAgent}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label htmlFor="status" className="block text-sm font-medium text-gray-700">Status</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        id="status"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  name="status"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={formData.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="active">Active</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="inactive">Inactive</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="suspended">Suspended</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {errors.submit && <p className="text-sm text-red-600">{errors.submit}</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex justify-end space-x-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={onCancel}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-gray-700 bg-gray-100 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Cancel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {initialData ? 'Update Account' : 'Add Account'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default AccountForm;