# backend/cloudformation/scheduler.yaml

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Scheduler for Mass DM Sender'

Resources:
  ProcessQueueSchedulerRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Trigger process_queue Lambda function every minute"
      ScheduleExpression: "rate(1 minute)"
      State: "ENABLED"
      Targets: 
        - Arn: !GetAtt ProcessQueueLambdaFunction.Arn
          Id: "ProcessQueueLambdaFunction"

  ProcessQueueLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: process_queue
      Handler: src.lambda_functions.process_queue.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: your-deployment-bucket
        S3Key: process_queue_lambda.zip
      Runtime: python3.8
      Timeout: 60

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SQSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt MessageQueue.Arn

  MessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: mass-dm-sender-queue

Outputs:
  QueueURL:
    Description: "URL of the SQS Queue"
    Value: !Ref MessageQueue